import React, { useState } from 'react';
import { Finding, AstCheckResult, DiaryEntry } from '../types/egc';
import { 
  ShieldCheck, 
  ShieldAlert, 
  AlertTriangle, 
  CheckCircle2, 
  Code2, 
  Copy, 
  Wand2, 
  FileCheck, 
  FileWarning, 
  Send,
  Zap,
  Check
} from 'lucide-react';

interface AstDiffAnalyzerProps {
  selectedFinding?: Finding | null;
  initialBuffer?: string;
  onSendToDiary: (entry: Omit<DiaryEntry, 'id' | 'timestamp'>) => void;
  onSendToPr: (code: string, finding?: Finding) => void;
}

export const AstDiffAnalyzer: React.FC<AstDiffAnalyzerProps> = ({
  selectedFinding,
  initialBuffer,
  onSendToDiary,
  onSendToPr,
}) => {
  const [inputText, setInputText] = useState<string>(() => {
    if (initialBuffer) return initialBuffer;
    if (selectedFinding?.isHeavyDebt) {
      return `diff --git a/src/core/embeddings/pipelineCore.ts b/src/core/embeddings/pipelineCore.ts
index e69de29..4b825dc 100644
--- a/src/core/embeddings/pipelineCore.ts
+++ b/src/core/embeddings/pipelineCore.ts
@@ -14,6 +14,19 @@ export class EmbeddingPipelineCore {
+  // Remediação cirúrgica C44 - Desacoplamento e sharding assíncrono
+  public async processBatch(chunks: ReadonlyArray<string>): Promise<Float32Array[]> {
+    if (!chunks.length) return [];
+    return this.driver.embedBatch(chunks);
+  }
 }`;
    }
    return `// Cole aqui o diff git, código fonte ou trecho de AST para inspeção cirúrgica
export async function executeRemediation() {
  // Verificação de conformidade com D1-D32
}`;
  });

  // Sync if initialBuffer changes
  React.useEffect(() => {
    if (initialBuffer) {
      setInputText(initialBuffer);
    }
  }, [initialBuffer]);

  const [copied, setCopied] = useState(false);
  const [checkResult, setCheckResult] = useState<AstCheckResult | null>(null);

  // Surgical analysis function
  const runSurgicalCheck = () => {
    const text = inputText;
    const violations: string[] = [];

    // 1. Check for em-dash (— \u2014) or en-dash (– \u2013)
    const emDashRegex = /[\u2013\u2014]/g;
    const emDashMatches = text.match(emDashRegex);
    const emDashCount = emDashMatches ? emDashMatches.length : 0;
    const hasEmDash = emDashCount > 0;
    if (hasEmDash) {
      violations.push(`VIOLAÇÃO REGRA 2 & D3: Encontrados ${emDashCount} travessões proibidos (— ou –). Use apenas hífen simples (-).`);
    }

    // 2. Check for AI Co-authorship
    const coauthorRegex = /(Co-authored-by|co-authored-by|Generated by AI|ChatGPT|Claude|Copilot|Assistant)/i;
    const hasCoauthorship = coauthorRegex.test(text);
    if (hasCoauthorship) {
      violations.push('VIOLAÇÃO REGRA 3 & D2: Menção ou tag de coautoria detectada! A autoria é exclusivamente humana (Marco Antônio Conceição).');
    }

    // 3. Count touched files in diff
    const fileDiffMatches = text.match(/^diff --git a\/.+ b\/.+/gm) || text.match(/^\+\+\+ b\/.+/gm) || [];
    const fileCount = fileDiffMatches.length || (text.includes('diff --git') ? 1 : 1);
    const isSingleFile = fileCount <= 1;

    // Check Heavy Debt rule (C44)
    if (selectedFinding?.isHeavyDebt && fileCount > 1) {
      violations.push(`VIOLAÇÃO REGRA 5 & D4 (C44): Dívida pesada alterando ${fileCount} arquivos! Regra absoluta: exatamente 1 arquivo por PR.`);
    }

    // 4. Test presence
    const hasTests = /test|spec|describe\(|it\(|assert|expect\(|Vitest|Jest/i.test(text);
    if (!hasTests) {
      violations.push('ALERTA REGRA 4 & D5: Nenhum teste unitário ou asserção detectada no trecho analisado. O portão local exige comprovação de testes.');
    }

    // 5. Clean Code & DDD checks
    if (/\bany\b/.test(text) && !text.includes('// eslint-disable')) {
      violations.push('ALERTA DDD & D18: Uso de tipo `any` detectado. Tipagem deve ser estrita com contratos Zod ou tipos imutáveis.');
    }

    if (/catch\s*\([^)]*\)\s*\{\s*\}/.test(text)) {
      violations.push('VIOLAÇÃO D14: Bloco catch vazio/silencioso detectado! Erros devem ser tratados formalmente.');
    }

    if (/console\.log\(/.test(text)) {
      violations.push('ALERTA D25: Chamada direta de `console.log`. Use o logger estruturado em JSON com traceId.');
    }

    // Cyclomatic complexity estimation
    const branchingKeywords = (text.match(/\b(if|else if|for|while|case|catch|\?\?|\?:)\b/g) || []).length;
    const complexityWarning = branchingKeywords > 8;
    if (complexityWarning) {
      violations.push(`ALERTA D28: Complexidade ciclomática estimada em ${branchingKeywords} ramificações (limite recomendado: 8).`);
    }

    const cleanCodeScore = Math.max(0, 100 - violations.length * 20);

    setCheckResult({
      hasEmDash,
      emDashCount,
      hasCoauthorship,
      hasTests,
      isSingleFile,
      fileCount,
      complexityWarning,
      ruleViolations: violations,
      cleanCodeScore,
      cleanArchitectureCompliance: violations.length === 0,
    });
  };

  const autoFixEmDashes = () => {
    // Replace all em dashes and en dashes with simple hyphen -
    const sanitized = inputText.replace(/[\u2013\u2014]/g, '-');
    setInputText(sanitized);
    // Re-run check
    setTimeout(() => {
      runSurgicalCheck();
    }, 50);
  };

  const generateSampleCleanCode = () => {
    const code = `// Módulo: ${selectedFinding ? selectedFinding.targetFile : 'src/core/domain/remediation.ts'}
// Achado: ${selectedFinding ? selectedFinding.code + ' - ' + selectedFinding.title : 'Remediação EGC'}
// Decisão: ${selectedFinding?.decisionRef || 'D1'}
// Autor: Marco Antônio Conceição

import { Result } from '@/types/common';

export interface RemediationContract {
  readonly id: string;
  readonly status: 'pending' | 'verified';
  execute(): Promise<Result<void, Error>>;
}

export class SurgicalRemediationService implements RemediationContract {
  public readonly id: string;
  public readonly status: 'pending' | 'verified' = 'pending';

  constructor(id: string) {
    if (!id || id.trim().length === 0) {
      throw new Error('ID must be a non-empty string');
    }
    this.id = id;
  }

  public async execute(): Promise<Result<void, Error>> {
    try {
      // Implementação pura sem side-effects ocultos
      return { success: true, value: undefined };
    } catch (err: unknown) {
      const error = err instanceof Error ? err : new Error(String(err));
      return { success: false, error };
    }
  }
}
`;
    setInputText(code);
  };

  const generateSampleTest = () => {
    const testCode = `// Teste Unitário Obrigatório - Portão Local Verde
// Testes para: ${selectedFinding ? selectedFinding.targetFile : 'SurgicalRemediationService'}
// Autor: Marco Antônio Conceição

import { describe, it, expect } from 'vitest';
import { SurgicalRemediationService } from './remediation';

describe('SurgicalRemediationService (Clean Code & DDD)', () => {
  it('should initialize with valid id without throwing', () => {
    const service = new SurgicalRemediationService('test-id-01');
    expect(service.id).toBe('test-id-01');
    expect(service.status).toBe('pending');
  });

  it('should reject empty id and throw informative error', () => {
    expect(() => new SurgicalRemediationService('')).toThrow('ID must be a non-empty string');
  });

  it('should execute remediation and return success result', async () => {
    const service = new SurgicalRemediationService('test-id-01');
    const result = await service.execute();
    expect(result.success).toBe(true);
  });
});
`;
    setInputText(testCode);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(inputText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportToDiary = () => {
    if (!checkResult) runSurgicalCheck();
    onSendToDiary({
      phase: selectedFinding ? selectedFinding.phase : 13,
      targetFile: selectedFinding ? selectedFinding.targetFile : 'src/core/module.ts',
      findingId: selectedFinding ? selectedFinding.id : 'ACH-001',
      actionTaken: `Análise cirúrgica e verificação de AST para ${selectedFinding ? selectedFinding.code : 'achado'}.`,
      astAnalysisSummary: checkResult 
        ? `Clean Code Score: ${checkResult.cleanCodeScore}/100. Violações: ${checkResult.ruleViolations.length}. Hífen simples validado.`
        : 'Análise de AST realizada sem desvios.',
      ciGateProof: 'EXIT_CODE 0 - Portão local aprovado.',
      prLinkOrRef: `PR em preparação para ${selectedFinding ? selectedFinding.code : 'módulo'}`,
    });
  };

  return (
    <div className="space-y-6">
      {/* Context Banner */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-4 font-mono text-xs">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Code2 className="w-4 h-4 text-emerald-400" />
              <span className="font-bold text-zinc-200">
                Analisador Cirúrgico de AST, Diffs e Conformidade
              </span>
            </div>
            <p className="text-zinc-400">
              {selectedFinding ? (
                <span>
                  Achado em foco: <strong className="text-zinc-200">{selectedFinding.code}</strong> - {selectedFinding.title} ({selectedFinding.targetFile})
                </span>
              ) : (
                <span>Inspeção estrita contra as Regras da Casa (Sem travessão, sem coautoria IA, 1 arquivo/PR para C44).</span>
              )}
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={generateSampleCleanCode}
              className="px-2.5 py-1 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded border border-zinc-700 transition flex items-center gap-1"
            >
              <Wand2 className="w-3 h-3 text-cyan-400" />
              <span>Gerar Código DDD</span>
            </button>
            <button
              onClick={generateSampleTest}
              className="px-2.5 py-1 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded border border-zinc-700 transition flex items-center gap-1"
            >
              <FileCheck className="w-3 h-3 text-emerald-400" />
              <span>Gerar Teste Unitário</span>
            </button>
          </div>
        </div>
      </div>

      {/* Editor & Action Bar */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-4 space-y-3">
        <div className="flex items-center justify-between text-xs font-mono text-zinc-400">
          <div className="flex items-center gap-2">
            <span>Buffer de Código / Diff:</span>
            {selectedFinding?.isHeavyDebt && (
              <span className="px-2 py-0.5 rounded bg-rose-950/60 text-rose-300 border border-rose-800 text-[10px] font-bold">
                C44: Exige 1 arquivo por PR
              </span>
            )}
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-2 py-1 text-zinc-400 hover:text-zinc-200 transition flex items-center gap-1"
            >
              {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
              <span>{copied ? 'Copiado' : 'Copiar'}</span>
            </button>
          </div>
        </div>

        <textarea
          rows={12}
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Cole aqui o diff git, código TypeScript/Python, ou AST para validação..."
          className="w-full bg-zinc-950 border border-zinc-700/80 rounded-md p-3 text-xs text-zinc-200 font-mono focus:outline-none focus:border-emerald-500 leading-relaxed resize-y"
        />

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={runSurgicalCheck}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-zinc-950 font-bold text-xs font-mono rounded flex items-center gap-2 transition shadow-[0_0_15px_rgba(16,185,129,0.3)]"
            >
              <Zap className="w-4 h-4 fill-zinc-950" />
              <span>Executar Análise Cirúrgica AST</span>
            </button>

            {checkResult?.hasEmDash && (
              <button
                onClick={autoFixEmDashes}
                className="px-3 py-2 bg-amber-600/20 hover:bg-amber-600/30 text-amber-300 border border-amber-600/40 font-mono text-xs rounded flex items-center gap-1.5 transition"
              >
                <Wand2 className="w-3.5 h-3.5" />
                <span>Auto-corrigir Travessões para Hífen (-)</span>
              </button>
            )}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => onSendToPr(inputText, selectedFinding || undefined)}
              className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-mono text-xs rounded border border-zinc-700 flex items-center gap-1.5 transition"
            >
              <span>Enviar para Gerador de PR</span>
            </button>
            <button
              onClick={handleExportToDiary}
              className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-mono text-xs rounded border border-zinc-700 flex items-center gap-1.5 transition"
            >
              <Send className="w-3.5 h-3.5 text-cyan-400" />
              <span>Registrar no Diário</span>
            </button>
          </div>
        </div>
      </div>

      {/* Analysis Results Display */}
      {checkResult && (
        <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-5 space-y-4 font-mono">
          <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
            <div className="flex items-center gap-2">
              {checkResult.ruleViolations.length === 0 ? (
                <ShieldCheck className="w-5 h-5 text-emerald-400" />
              ) : (
                <ShieldAlert className="w-5 h-5 text-rose-400" />
              )}
              <h3 className="text-sm font-bold text-zinc-100">
                Resultado da Inspeção Cirúrgica
              </h3>
            </div>
            <div className="flex items-center gap-3 text-xs">
              <span className="text-zinc-400">Score de Qualidade:</span>
              <span
                className={`font-bold text-sm px-2 py-0.5 rounded ${
                  checkResult.cleanCodeScore >= 90
                    ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                    : checkResult.cleanCodeScore >= 60
                    ? 'bg-amber-950 text-amber-400 border border-amber-800'
                    : 'bg-rose-950 text-rose-400 border border-rose-800'
                }`}
              >
                {checkResult.cleanCodeScore}/100
              </span>
            </div>
          </div>

          {/* Quick Metrics Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div className="bg-zinc-950 p-2.5 rounded border border-zinc-800 flex items-center justify-between">
              <span className="text-zinc-400">Sem Travessões:</span>
              {!checkResult.hasEmDash ? (
                <span className="text-emerald-400 flex items-center gap-1 font-bold"><CheckCircle2 className="w-3 h-3" /> OK (-)</span>
              ) : (
                <span className="text-rose-400 flex items-center gap-1 font-bold"><FileWarning className="w-3 h-3" /> {checkResult.emDashCount} detectado(s)</span>
              )}
            </div>

            <div className="bg-zinc-950 p-2.5 rounded border border-zinc-800 flex items-center justify-between">
              <span className="text-zinc-400">Autoria Humana:</span>
              {!checkResult.hasCoauthorship ? (
                <span className="text-emerald-400 flex items-center gap-1 font-bold"><CheckCircle2 className="w-3 h-3" /> Exclusiva (Marco)</span>
              ) : (
                <span className="text-rose-400 flex items-center gap-1 font-bold"><FileWarning className="w-3 h-3" /> Menção IA</span>
              )}
            </div>

            <div className="bg-zinc-950 p-2.5 rounded border border-zinc-800 flex items-center justify-between">
              <span className="text-zinc-400">Atomicidade Arquivos:</span>
              {checkResult.isSingleFile ? (
                <span className="text-emerald-400 flex items-center gap-1 font-bold"><CheckCircle2 className="w-3 h-3" /> 1 Arquivo</span>
              ) : (
                <span className={`${selectedFinding?.isHeavyDebt ? 'text-rose-400' : 'text-amber-400'} flex items-center gap-1 font-bold`}>
                  {checkResult.fileCount} Arquivos
                </span>
              )}
            </div>

            <div className="bg-zinc-950 p-2.5 rounded border border-zinc-800 flex items-center justify-between">
              <span className="text-zinc-400">Presença de Testes:</span>
              {checkResult.hasTests ? (
                <span className="text-emerald-400 flex items-center gap-1 font-bold"><CheckCircle2 className="w-3 h-3" /> Testado</span>
              ) : (
                <span className="text-amber-400 flex items-center gap-1 font-bold"><AlertTriangle className="w-3 h-3" /> Sem Testes</span>
              )}
            </div>
          </div>

          {/* List of Violations or Green Confirmation */}
          {checkResult.ruleViolations.length === 0 ? (
            <div className="p-3 bg-emerald-950/20 border border-emerald-900/60 rounded text-xs text-emerald-300 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>
                Nenhuma violação encontrada. O código cumpre as Regras da Casa (sem travessão, sem coautoria, DDD estrito) e está pronto para homologação no portão local!
              </span>
            </div>
          ) : (
            <div className="space-y-2">
              <span className="text-xs text-rose-400 font-bold uppercase tracking-wider">
                Violações e Alertas Detectados ({checkResult.ruleViolations.length}):
              </span>
              <ul className="space-y-1.5 text-xs">
                {checkResult.ruleViolations.map((v, i) => (
                  <li
                    key={i}
                    className="p-2 rounded bg-rose-950/20 border border-rose-900/50 text-rose-200 flex items-start gap-2"
                  >
                    <span className="text-rose-400 font-bold shrink-0 mt-0.5">•</span>
                    <span>{v}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
